In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


In [2]:
random_tensor = torch.rand(7, 7)
random_tensor, random_tensor.shape

(tensor([[0.9377, 0.1770, 0.7848, 0.5770, 0.8603, 0.7679, 0.3090],
         [0.3295, 0.7184, 0.0320, 0.5916, 0.2854, 0.7742, 0.5654],
         [0.0960, 0.6740, 0.4551, 0.6901, 0.8144, 0.3292, 0.4847],
         [0.7803, 0.2367, 0.2414, 0.8066, 0.9918, 0.8434, 0.8576],
         [0.3028, 0.1273, 0.2866, 0.2929, 0.2895, 0.8279, 0.0200],
         [0.8423, 0.1787, 0.8312, 0.8203, 0.8061, 0.7048, 0.8775],
         [0.0082, 0.3969, 0.0738, 0.3703, 0.8997, 0.6274, 0.0734]]),
 torch.Size([7, 7]))

In [3]:
random_tensor_2 = torch.rand(1, 7)
random_tensor_2

tensor([[0.3286, 0.2157, 0.5502, 0.5244, 0.7155, 0.5371, 0.5907]])

In [4]:
# Multiplying the tensors with transposed
torch.matmul(random_tensor, random_tensor_2.T)

tensor([[2.2911],
        [1.5450],
        [1.8350],
        [2.5325],
        [1.1018],
        [2.6764],
        [1.3470]])

In [5]:
# 4. Set the random seed to 0 and do exercises 2 & 3 over again.

RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

random_tensor = torch.rand(7, 7)
random_tensor_2 = torch.rand(1, 7)
random_tensor, random_tensor_2, torch.matmul(random_tensor, random_tensor_2.T)


(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]]),
 tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]))

In [6]:
# 5.

In [7]:
MANUAL_SEED_CUDA=1234

torch.cuda.manual_seed(MANUAL_SEED_CUDA)

In [8]:
# 6. Create two random tensors of shape (2, 3) and send them both to the GPU

In [9]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [11]:
random_tensor_cuda = torch.rand(2, 3)
random_tensor_cuda_2 = torch.rand(2, 3)
random_tensor_cuda.is_cuda, random_tensor_cuda_2.is_cuda

(False, False)

In [25]:
## This doesn't work
MANUAL_SEED_CUDA=1234

torch.cuda.manual_seed(MANUAL_SEED_CUDA)

random_tensor_cuda = torch.rand(2, 3).cuda()
random_tensor_cuda_2 = torch.rand(2, 3).cuda()
random_tensor_cuda.is_cuda, random_tensor_cuda_2.is_cuda

(True, True)

In [26]:
random_tensor_cuda, random_tensor_cuda_2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [35]:
# This does work

MANUAL_SEED_CUDA=1234

torch.cuda.manual_seed(MANUAL_SEED_CUDA)

random_tensor_cuda = torch.rand((2, 3), device=device)
random_tensor_cuda_2 = torch.rand((2, 3),device=device )
random_tensor_cuda.is_cuda, random_tensor_cuda_2.is_cuda

(True, True)

In [36]:
random_tensor_cuda, random_tensor_cuda_2

(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.6208, 0.0276, 0.3255],
         [0.1114, 0.6812, 0.3608]], device='cuda:0'))

In [39]:
# 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

result = torch.matmul(random_tensor_cuda, random_tensor_cuda_2.T)
result

tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')

In [41]:
# 8. Find the maximum and minimum values of the output of 7.

# Minimum
torch.min(result), result.min()

(tensor(0.2786, device='cuda:0'), tensor(0.2786, device='cuda:0'))

In [42]:
# Maximum
torch.max(result), result.max()

(tensor(0.7668, device='cuda:0'), tensor(0.7668, device='cuda:0'))

In [43]:
# 9. Find the maximum and minimum index values of the output of 7.

# Minimum index
result.argmin()

tensor(0, device='cuda:0')

In [44]:
# Maximum index
result.argmax()

tensor(1, device='cuda:0')

### 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [54]:
MANUAL_SEED_CUDA = 7

torch.cuda.manual_seed(MANUAL_SEED_CUDA)

random_10_dim = torch.rand((1, 1, 1, 10), device=device)
random_10_dim_squeeze = random_10_dim.squeeze()

print(f"First tensor: {random_10_dim},\nits shape: {random_10_dim.shape}")
print(f"Second tensor: {random_10_dim_squeeze},\nits shape: {random_10_dim_squeeze.shape}")


First tensor: tensor([[[[0.9546, 0.4950, 0.9420, 0.5926, 0.6996, 0.2087, 0.6753, 0.4810,
           0.6333, 0.5733]]]], device='cuda:0'),
its shape: torch.Size([1, 1, 1, 10])
Second tensor: tensor([0.9546, 0.4950, 0.9420, 0.5926, 0.6996, 0.2087, 0.6753, 0.4810, 0.6333,
        0.5733], device='cuda:0'),
its shape: torch.Size([10])
